version: '3.3'

services:
  server:
    image: joshandromidas/api-overview
    ports:
      - '5005:5005'
    environment:
      - HOST=pg-database
      - USER=docker
      - PASS=your_password_here
      - DB=products_db
    volumes:
      - server:/app # SAME DATA
      # - data:/pg_database
  pg-database:
    image: postgres
    container_name: pg-database
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: your_password_here
      POSTGRES_DB: products_db
    volumes:
      # - data:/var/lib/postgresql/data
      - server:/app/server # SAME DATA

volumes:
  data:
  server:

    # pg_dump database > file.pgsql
