version: '3.9'

services:
  server:
    build: .
    ports:
      - '5005:5005'
    environment:
      - HOST=db
      - USER=docker
      - PASS=asdf1234
      - DB=products_db
      - PORT=5005
    volumes:
      - source_files:/app/source_files
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: asdf1234
    volumes:
      - data:/var/lib/postgresql/data
      - source_files:/app/source_files

volumes:
  data:
  source_files:
